### ISSUE TITLE
Feature Suggestion: Improving Performance by Optionally Disabling Client-side Execution

### ISSUE THREAD

**Issue by ZCK12** [celestialorb/factorio-prometheus-exporter#16]
Now that the metrics interval can be set with a mod option, I was able to diagnose some minor hitching happening for my friends connected to the server. They are small freezes that happen exactly as the mod is gathering the internal statistics and last for maybe 50ms.

People with slower computers seem to experience longer freezes, so I think this is caused by the mod gathering statistics locally on client machines rather than from the server itself. 

I thought this might be from file I/O, so I changed the file permissions to block all writes into metrics json file. This didn't seem to affect the freezes at all, so I feel like the issue purely stems from enumerating the internal Factorio stats rather than disk I/O.

**Would it be possible to create a mod option which disables gathering stats on client machines?**

**Comment by celestialorb** [comment]
Yes! It would certainly be possible and I was actually thinking of adding this in soon. Unfortunately my workstation died this week and so I'm out of commission until my new one arrives (or I replace the borked motherboard).

I have a backup laptop that I could create the feature on, but testing it would be very slow as it's nearly seven years old and Factorio takes a while to load...though it actuallly might be the perfect candidate for testing for a difference in performance now that I think about it.

**Comment by celestialorb** [comment]
One issue that I can think of is, what value should be used as the default for enabling the exporting of metrics? I think defaulting to enabled is the best way since it (a) preserves current behavior and (b) makes installing the mod all that's necessary (no need to go into the settings to enable it).

However, I'd kind of want the mod to automatically be disabled client-side but there's not a way to distinguish if we're running "client-side" or "server-side" in Factorio, meaning everyone who installs the mod in order to join the server will then need to disable it if it affects their performance. I'm pretty sure that's the best we can do here.

**Comment by ZCK12** [comment]
I was also thinking about how to differentiate between client/server. I know the write_file helper function has an optional for_player? argument that disables writing to client folders. But I can't think of how to prevent executing the data collection part of the script using this...

**Comment by celestialorb** [comment]
I've been looking into this today and I'm really struggling to find a way to disable it client-side. By design, Factorio mods are intended to run in exactly the same manner between server and client in order to preserve determinism so that makes this difficult; a client can't simply choose to have different mod settings than the server. As a result of that design, all mod settings between clients and the server _must_ match.

I was thinking I could leverage the settings-per-user option but unfortunately I don't think that would work either as I'd need to know the player associated with the Factorio instance running and that doesn't seem to be available in any context.

I don't think using the `write_file` helper would work either as AFAIK there isn't a way to read any external files so a setting can't be passed that way.

This might be possible by somehow abusing RCON, but I'm not confident and I'm not sure I'd want to really dig into that option to solve this.

Until we can figure out a way to either be able to associate the player of the current Factorio instance or otherwise have differing behavior between Factorio instances I don't think we can disable it client-side. I'd recommend setting a higher value for the metrics interval, as the default of 60 -- being once every 60 ticks -- is once per second, which is likely higher than you'd need anyway for a standard Prometheus + Grafana setup. If your Prometheus is scraping every 15 seconds you can set a metrics interval of 900 to match it, or 3600 if Prometheus is scraping every minute.

**Comment by ZCK12** [comment]
Fair enough mate. This would be bending rules of Factorio's deterministic system, so it makes sense there's no straightforward way to do this.

It's a shame since obviously this mod wouldn't desynchronise game state, but that doesn't mean we're above the rules. Lock-step it is 😄

**Comment by ChrislyBear-GH** [comment]
How about trying to write a file only on the host machine - this could be a player hosted server or a dedicated server - and test for it?? Not sure if this works, but maybe that's a way to go.

```lua
-- control.lua

-- Function to determine if the current instance is the server or the host player
local function is_server()
    local test_filename = "__IsServerTest__.txt"
    local test_content = "server_check"

    -- Last parameter "for_player" = 0 only writes on the server. See LuaHelpers.html#write_file
    local success, _ = pcall(function()
        game.write_file(test_filename, test_content, false, 0)
    end)

    return success
end

-- Function to collect and write metrics
local function collect_metrics()
-- .... logic that runs in under 1/60th of a second!! if not, split the workload!....
    -- Serialize data to JSON and write to file 
    local json = game.table_to_json(data)
    game.write_file("metrics_log.txt", json .. "\n", true)
end

-- Event handler to collect metrics every 600 ticks (10 seconds)
script.on_nth_tick(600, function(event)
    if is_server() then
        collect_metrics()
    end
end)

```

**Comment by celestialorb** [comment]
> ```lua
> LuaHelpers.html#write_file
> ```

Hrm, that might work. I missed the part of `providing 0 will only write to the server's output if present.`. The question here is what is "the server" in this context. I have a feeling that providing `0` would still write the file out on all Factorio instances. I think I could test this by copying my local mod to a server I have setup so that the checksums match and I can join it.

Aside from this, I've been pondering on other solutions to the main issue:

Option (1) would be to identify the slow parts of metric collection and reduce the frequency of more resource-intensive collections (or add settings to configure how often certain metrics are collected).

Option (2) would be to potentially skip metric collection all together and write out larger blocks of data and let the Prometheus exporter be the component responsible for filtering through it for the metrics we're interested in. Though I'm fairly certain the additional time taken to write out the extra data to disk would be greater than the time saved by not looping through and filtering out for the metrics we're interested in; could try and see if I can test it though.

**Comment by ChrislyBear-GH** [comment]
Yes, that's a point of uncertainty, that I'm currently testing myself with a copy of your mod. How is a dedicated server and a player hosted game behaving differently when supplying a 0 for write file.

If it's the same, then we might have won the jackpot. If not, further investigaion is necessary.

**Comment by ZCK12** [comment]
It feels like we're going down the rabbit hole a bit here 😄

I like the idea of spacing out the metrics collection. While it adds complexity to an otherwise very simple mod, it would definitely improve performance. 

On a side note... while I don't have any experience with Factorio mods, I feel like the scheduling logic there might be overkill. Could it be reduced to something along the lines of this:   
```lua
local index = (current_tick % #metric_functions) + 1
-- extra code for delays between gathering, or between batches.
local func = metric_functions[index]
if func then
    func()
end
```
Then register it to run every tick? It would save the complexity of trying to schedule events in the future as well as making the code stateless.

**Comment by ChrislyBear-GH** [comment]
I think the "extra code to delay stuff" is exactly what I wrote above 😂

Only taking the mod and hoping for the best won't be enough, I think. In my opinion it should be more event based than tick based. E.g. update build statistic only if something has been built or destroyed. This saves valuable compute time.

I don't think going completely stateless would be beneficial, because the metrics themselves are already carried along and are part of the mod's state. Completely stateless would mean having to dump all the stats every time, but that's too expensive.

I had a look at other stats mods like graftorio2 etc.: They are very event based and run only every 5 minutes or so.

Where to go from here exactly... I'm not sure. It seems like dumping stats is rather costly, which is a pity.

Chris

**Comment by celestialorb** [comment]
Hrm, my initial thought when authoring this mod was that updating on events would likely end up being more process-intensive than updating periodically (e.g. updating every time an item is produced could cause tons of updates per second versus updating the number of items produced periodically once a second).

I think the next step for me is to start profiling some of these sections of code. For example the `get_item_production_statistics()` may be more expensive than I had assumed. Looks like Factorio comes with [a profiler](https://lua-api.factorio.com/latest/classes/LuaProfiler.html) so I'll get started on collecting some data.

Also, thanks for the input! Really hoping to get this mod in state where it can be used without performance issues.

@ChrislyBear-GH @ZCK12 By the way, what's the state of your saves when you experience the performance issues? I haven't encountered them personally but all my saves are in early-game states and I haven't touched any of the Space Age DLC yet. Do you experience it in early-game?

**Comment by ChrislyBear-GH** [comment]
I'm currently at a rather early state in the game and I'm running it on a quite capable server. Not sure why the stat collection takes so long.

Since this really felt like a rabbit hole, I have changed my approach: I have taken the apporach of https://github.com/janten/factorio-stats and I'm now running a little python container, that serves stats on demand directly to prometheus!
The stats are gathered via RCON and aren't impacting the game performance anymore! Not sure why this is different though.
The advantage is that this approach doesn't requre any mod at all!

I have revised the LUA script, that is executed on a scrape. This is my version:

```lua
-- gather-stats.lua

rcon.print('factorio_tick ' .. game.tick)
rcon.print('factorio_ticks_played ' .. game.ticks_played)
rcon.print('factorio_connected_players ' .. #game.connected_players)

if #game.connected_players > 0 then 


    for k, force in pairs(game.forces) do
        rcon.print('factorio_rockets_launched{force="' .. force.name .. '"} ' .. force.rockets_launched)
        rcon.print('factorio_research_progress{force="' .. force.name .. '"} ' .. force.research_progress)
        for _, item in ipairs(force.items_launched) do
            rcon.print('factorio_items_launched{force="' .. force.name .. '", name="' .. item.name or "nil" .. '", count="' .. item.count or 0 .. '", quality="' .. item.quality .. '"} ')
        end
        for surface, _ in pairs(game.surfaces) do
            for entity, amount in pairs(force.get_kill_count_statistics(surface).input_counts) do
                rcon.print('factorio_killed{surface="' .. surface .. '", force="' .. force.name .. '", name="' .. entity .. '"} ' .. amount)
            end
            for entity, amount in pairs(force.get_kill_count_statistics(surface).output_counts) do
                rcon.print('factorio_killed_by{surface="' .. surface .. '", force="' .. force.name .. '", name="' .. entity .. '"} ' .. amount)
            end
            for item, amount in pairs(force.get_item_production_statistics(surface).input_counts) do
                rcon.print('factorio_production{surface="' .. surface .. '", type="item", force="' .. force.name .. '", name="' .. item .. '"} ' .. amount)
            end
            for item, amount in pairs(force.get_item_production_statistics(surface).output_counts) do
                rcon.print('factorio_consumption{surface="' .. surface .. '", type="item", force="' .. force.name .. '", name="' .. item .. '"} ' .. amount)
            end
            for fluid, amount in pairs(force.get_fluid_production_statistics(surface).input_counts) do
                rcon.print('factorio_production{surface="' .. surface .. '", type="fluid", force="' .. force.name .. '", name="' .. fluid .. '"} ' .. amount)
            end
            for fluid, amount in pairs(force.get_fluid_production_statistics(surface).output_counts) do
                rcon.print('factorio_consumption{surface="' .. surface .. '", type="fluid", force="' .. force.name .. '", name="' .. fluid .. '"} ' .. amount)
            end
            for entity, amount in pairs(force.get_entity_build_count_statistics(surface).input_counts) do
                rcon.print('factorio_production{surface="' .. surface .. '", type="entity", force="' .. force.name .. '", name="' .. entity .. '"} ' .. amount)
            end
            for entity, amount in pairs(force.get_entity_build_count_statistics(surface).output_counts) do
                rcon.print('factorio_consumption{surface="' .. surface .. '", type="entity", force="' .. force.name .. '", name="' .. entity .. '"} ' .. amount)
            end
        end
    end
    for surface, _ in pairs(game.surfaces) do
        for pol_ent, amount in pairs(game.get_pollution_statistics(surface).input_counts) do
            rcon.print('factorio_production{surface="' .. surface .. '", type="pollution", force="player", name="' .. pol_ent .. '"} ' .. amount)
        end
        for pol_ent, amount in pairs(game.get_pollution_statistics(surface).output_counts) do
            rcon.print('factorio_consumption{surface="' .. surface .. '", type="pollution", force="player", name="' .. pol_ent .. '"} ' .. -amount)
        end
    end

end
```

I'm currently gathering the stats every 10 seconds and I don't notice anything, no stutter at all. The only thing missing for me are energy statistics. Maybe I'll extend the script soon.

Chris

**Comment by celestialorb** [comment]
Hrm, interesting approach. Use of RCON might mean that people will need to additionally expose the RCON port, but maybe not if they run the exporter as a sidecar in Kubernetes. Would certainly love to remove the need to install a mod as it increases the development turnaround time and installation complexity!

I'll experiment with this approach and see if it works for me as well, thanks! Would also mean that clients aren't exporting metrics!

**Comment by celestialorb** [comment]
Hitting some minor downsides to using RCON for this. One of them is that it seems each RCON command issued advances the game by one tick, meaning that even if no one is online the game will continue to run, though the rate at which will depend on how often scraping is occurring.

We can control whether or not the game is paused from the RCON commands, so we can pause it if no one is online, but this means when a player joins we'd have to wait until the next scrape for the RCON command to unpause the game. We could have another thread performing the pause/unpause at a higher rate to avoid this though, but this might interfere with other mods that have autopause features.

From my investigations today I think this is primarily stemming from the collection of the entity count. I think it would be best to disable / remove the entity count metric until I can break up the collection of that particular metric.

**Comment by celestialorb** [comment]
Been working on an RCON-only implementation of it this evening and believe I have it in a working and performant state, though with one fairly major change in design. I've split up the workload by separating out the metrics by group into different Prometheus endpoints (e.g. `/metrics/time`, `/metrics/production`, `/metrics/pollution`, etc.) which allows the user to independently scrape the metrics at different intervals, and/or leave out entire groups of metrics all together if collecting them is too process-intensive.

In order to provide _some_ sort of backwards compatability of the previous endpoint (even though this would still be a breaking change) the `/metrics` endpoint will change to `/metrics/all` and will collect and return all metrics.

I'll clean up the implementation tonight and hopefully have a release of a new container image later today or tomorrow.

**Comment by ZCK12** [comment]
You're doing god's work mate

**Comment by celestialorb** [comment]
@ZCK12 @ChrislyBear-GH I've gone ahead and released an early version of the RCON-implementation of this exporter. You can find the `v0.3.0-alpha` container image [here](https://github.com/celestialorb/factorio-prometheus-exporter/pkgs/container/factorio-prometheus-exporter/296023347?tag=v0.3.0-alpha).

Feel free to give it a try, and remember that you won't need the Factorio mod anymore so feel free to remove that from your servers if you're giving this early version a try!

If you need some help with configuring the exporter [the `README.md` file](https://github.com/celestialorb/factorio-prometheus-exporter/blob/e68f25c6649e92cc183812ae79e0b3920a0dcbd8/README.md) has been updated in #18 to reflect the new exporter.

Once I've put it under some more testing I'll merge it in and release a production version of it.

**Comment by oponder** [comment]
Hi just wanted to drop in and let you know I am appreciating this mod while exploring using it, and ran into this exact feature request as well.

I tried out the new container image and it's almost working fully for me.

Only the `/metrics/launches` endpoint causes an error. 
~And I noticed there is no more consumption metrics? Is that intentional or related to the disabled entity count metrics? For what it's worth I don't need entity count metrics.~ (never mind noticed its in the production endpoint)

I'm interested in making like a "net production" graph that would show me if I am accumulating resources somewhere.

Also personally don't mind that the RCON causes a tick on the server because I am playing around with the idea of having the factory running 24/7.

Just sharing in case it is helpful, if I decide to take my 24/7 idea further I might dig in myself and see if I can contribute something too. 

And for the record I don't mind about backwards compatibility :)

```
2024-12-08 18:51:33.560 | DEBUG    | collection.collectors:raw:120 - raw response: Cannot execute command. Error: [string "-- Lua script to be sent along as an RCON com..."]:16: attempt to index local 'item' (a number value)
WSGI application error
Traceback (most recent call last):
  File "/home/exporter/.local/lib/python3.13/site-packages/twisted/python/threadpool.py", line 285, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/home/exporter/.local/lib/python3.13/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/exporter/.local/lib/python3.13/site-packages/twisted/python/context.py", line 84, in callWithContext
    self.contexts.pop()
  File "/home/exporter/.local/lib/python3.13/site-packages/twisted/web/wsgi.py", line 492, in run
    self.started = True
--- <exception caught here> ---
  File "/home/exporter/.local/lib/python3.13/site-packages/twisted/web/wsgi.py", line 461, in run
    appIterator = self.application(self.environ, self.startResponse)
  File "/home/exporter/.local/lib/python3.13/site-packages/prometheus_client/exposition.py", line 128, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
  File "/home/exporter/.local/lib/python3.13/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
    output = encoder(registry)
  File "/home/exporter/.local/lib/python3.13/site-packages/prometheus_client/exposition.py", line 251, in generate_latest
    for metric in registry.collect():
  File "/home/exporter/.local/lib/python3.13/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/opt/exporter/collection/collectors.py", line 207, in collect
    metrics = self.metrics
  File "/opt/exporter/collection/collectors.py", line 131, in metrics
    return self.response["metrics"]
  File "/opt/exporter/collection/collectors.py", line 126, in response
    return json.loads(self.raw)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by celestialorb** [comment]
@oponder Thanks for the report! I'll take a look at it soon (hopefully).

**Comment by blackwhiser123** [comment]
I am wondering how could I get the fluid metric? It is not present in the /metrics/production. I am wondering if this is a mistake.

BTW, I love this new RCON feature, just running everything in Kubernetes, no issues running it all on my computer.

Thanks!

**Comment by blackwhiser123** [comment]
@celestialorb ,

I made some code change to your production collector and the collectors.py.

The changes made the script running smoother in Factorio, causing less FPS/UPS loss. Let me know if you want me to push my changes.

I removed the prototype_type and added support for fluid monitoring as it was not supported.

Giving metrics such as this:

![Image](https://github.com/user-attachments/assets/bf3f256b-4db1-40f6-90a2-35a8098362e7)

Thanks again for your work  :)

**Comment by celestialorb** [comment]
@blackwhiser123 Cool, thanks!

I haven't played Factorio in a while so this project has fallen off of my radar a bit. Could you create a PR with your changes, and in that PR could you describe how you implemented the performance improvements you mentioned?

Thanks again!

**Comment by blackwhiser123** [comment]
I would need permissions to create a PR :)

But mainly this is what I did: 

production.lua
`-- Lua script to be sent along as an RCON command to gather statistics and
-- report back metrics on the given world.
local response = {}
response["status"] = 200

local metrics = {}
metrics["forces"] = {}

for _, force in pairs(game.forces) do
  metrics["forces"][force.name] = {}
  for _, surface in pairs(game.surfaces) do
    metrics["forces"][force.name][surface.name] = {}
    metrics["forces"][force.name][surface.name]["prototypes"] = {}
    local production = game.forces[force.name].get_item_production_statistics(surface.name)
    local totals = production.input_counts
    for item_name, _ in pairs(totals) do
      metrics["forces"][force.name][surface.name]["prototypes"][item_name] = {}
      metrics["forces"][force.name][surface.name]["prototypes"][item_name]["production"] = production.get_input_count(item_name)
      metrics["forces"][force.name][surface.name]["prototypes"][item_name]["consumption"] = production.get_output_count(item_name)
    end
    local fluid_production = game.forces[force.name].get_fluid_production_statistics(surface.name)
    local fluid_totals = fluid_production.input_counts
    for item_name, _ in pairs(fluid_totals) do
      metrics["forces"][force.name][surface.name]["prototypes"][item_name] = {}
      metrics["forces"][force.name][surface.name]["prototypes"][item_name]["production"] = fluid_production.get_input_count(item_name)
      metrics["forces"][force.name][surface.name]["prototypes"][item_name]["consumption"] = fluid_production.get_output_count(item_name)
    end
  end
end

response["metrics"] = metrics
rcon.print(helpers.table_to_json(response))`

collector.py
` Line 282-296
        for force, force_data in metrics["forces"].items():
            for surface, surface_force_data in force_data.items():
                prototypes = surface_force_data["prototypes"]
                for prototype, prototype_data in prototypes.items():
                    force_consumption_stats.add_metric(
                        labels=[force, prototype, surface],
                        value=prototype_data["consumption"],
                    )
                    force_production_stats.add_metric(
                        labels=[force, prototype, surface],
                        value=prototype_data["production"],
                    )

        yield force_consumption_stats
        yield force_production_stats
`

**Comment by blackwhiser123** [comment]
@celestialorb,

I would need permissions to make a PR :)

Otherwise I commented on your PR with code change, which represents what I did. Nothing complicated 

Thanks!

**Comment by celestialorb** [comment]
@blackwhiser123 Are you able to fork the repository, make your changes on a branch, and then create a PR from there? I'm not aware of any setting preventing the creation of a PR from a fork in GitHub.

**Comment by blackwhiser123** [comment]
@celestialorb , this is the first project I contribute publicly. Sorry.

I created the fork  and the PR :)

**Comment by blackwhiser123** [comment]
@celestialorb , have a look at the PR, I added electricity (production, satisfaction and accumulator charge) metrics.
